zephyrproject-rtos/docker-image

- .shippable.yml
- Dockerfile
- README.md
> Add initial Docker file

- Dockerfile
Required by:
https://github.com/zephyrproject-rtos/zephyr/commit/d6eaf5f
Signed-off-by: Andy Doan <andy@foundries.io>
> Dockerfile: Bump to 0.10.0 SDK

- Dockerfile
> sdk: update to latest SDK

- .github/workflows/main.yml
Use GH actions to build docker image.
> ci: use actions to build docker image

- Dockerfile
Update with latest ARM toolchain.
> Dockerfile: update with latest tools

- Dockerfile
- README.md
If host user ID is not 1000, container user will not be able to modify workdir. So lets build container with same user ID as on host.
> Use host UID and GID for container user

- Dockerfile
Requirements were split, so download them all before we install.
> python: download all requirement files

- Dockerfile
Signed-off-by: John Grey <greyjohn734@gmail.com>
> Dockerfile: updated zephyr SDK to latest 0.12.0

- Dockerfile
Install the SDK 0.13.0-alpha-1 release in addition to SDK 0.12.4.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> Add SDK 0.13.0-alpha-1 release

- Dockerfile
Install the SDK 0.13.0-rc4 release for testing.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> Update to SDK 0.13.0-rc4 release

- Dockerfile
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> drop installing SDK 0.12.4

- Dockerfile
- Dockerfile.user
This commit reworks the Dockerfile such that:
* component installation steps are properly grouped and more logically
ordered.
* unnecessary image layers do not exist.
> Dockerfile overhaul

- Dockerfile
Needed for some CI scripts.
Signed-off-by: Anas Nashif <anas.nashif@intel.com>
> packages: add GitPython

- .github/workflows/ci.yml
- Dockerfile
This commit updates the Zephyr SDK version to 0.14.1.
> Update to Zephyr SDK 0.14.1

- .github/workflows/ci.yml
- Dockerfile.base
- Dockerfile.ci
- README.md
Add a new base layer without toolchains to allow for downstream
customization and usage with non zephyr-sdk toolchains.
Signed-off-by: Anas Nashif <anas.nashif@intel.com>
> add a new base layer without a toolchain

- Dockerfile.base
This series reworks the Python dependency installation step to fix dependency conflict issues.
Fixes https://github.com/zephyrproject-rtos/docker-image/issues/130
> Fix Python dependencies

- Dockerfile.base
Match the version bump in
https://github.com/zephyrproject-rtos/zephyr/pull/88055
> base: bump nrf-regtool to 9.0.1

- Dockerfile.ci
Install python 3.9 needed as a dependency.
Signed-off-by: Anas Nashif <anas.nashif@intel.com>
> fvp: install python 3.9

- .github/workflows/ci.yml
- Dockerfile.base
- Dockerfile.ci
- Dockerfile.devel
As of Docker version 23.0, BuildKit is the default builder and the heredoc syntax is therefore supported.
> Dockerfile: Use heredoc for multi-line RUN

- Dockerfile.base
- Dockerfile.ci
- Dockerfile.devel
Consolidate Dockerfile steps and perform a general clean-up of all the horrible mess we have.
Fixes https://github.com/zephyrproject-rtos/docker-image/issues/243
> Dockerfile: Consolidate steps
