zephyrproject-rtos/docker-image

- Dockerfile
The Zephyr build system now requires dtc-1.4.7. This isn't in Bionic
so we have to pull the deb directly from security pool.
Signed-off-by: Andy Doan <andy@foundries.io>
> Dockerfile: Use dtc 1.4.7

- Dockerfile
- entrypoint.sh
This PR adds the SDL2 library needed to build native_posix samples that make use of SDL display diver.
Further it includes a virtual frame buffer and VNC server on port 5900, the default password for the VNC server is ```zephyr```, that enables running the sample from inside the container.
When testing this PR make sure to open the port on the host machine via ```-p``` parameter:
```
docker run -it --rm -p 5900:5900 -v $PWD:/workdir zephyr:sdl
```
Note that documentation is not yet updated
> [RFC][DNM] SDL2 Display capable container

- README.md
Updated documentation on how the view, run and build native POSIX
samples that require a display.
> Updated documentation on display use

- Dockerfile
Install dos2unix command and run dos2unix on the entry point script.
This is need to guarantee that the entry point script is using Unix
line ending, if this is not the case the container will fail to
start.
Note that even if the entry point script is checked in with Unix line
ending cloning the repo on a windows system can change the line
ending to DOS depending on how git is installed on windows.
By default git will convert from Unix to DOS line ending while files
are checkout and convert back to Unix line ending on check in.
Fixes: #10
Signed-off-by: Jan Van Winkel <jan.van_winkel@dxplore.eu>
> Dockerfile: Added dos2unix and convert entry point

- Dockerfile
dtc-1.4.7-1 has been removed. Use dtc-1.4.7-3.
Signed-off-by: Jun-Ru Chang <jrjang@gmail.com>
> Dockerfile: fix dtc version

- Dockerfile
Package name was changed upstream for some reason.
You can view the package index here:
http://security.ubuntu.com/ubuntu/pool/main/d/device-tree-compiler/
> Fixed DTC package name

- Dockerfile
Build process exited with error because don't found Python.h provided by python3-dev package
> python: add python3-dev package needed by build process

- Dockerfile
SOLVED: modified requirements.txt breaks docker build due to manual download of sub-requirements files
ADDED: installing requirements from zephyrproject-rtos/mcuboot
Signed-off-by: John Grey <greyjohn734@gmail.com>
> Dockerfile: Fix requirements download

- Dockerfile
BUG: build was broken due to missing device-tree-compiler-1.4.7-1-3ubuntu2_amd64.deb from security.ubuntu.com
SOLUTION: removed evice-tree-compiler dependency. It is used for sanity check when checking own dts implementation result. When missing, using one from Zephyr SDK (current dts compiler 1.5.0-dirty in SDK 0.114), so this one is redundant.
IMPROVEMENT: moved wget commands to beginning of dockerfile, in case it fails because of missing sources, it fails early and not after apt install long operation
IMPROVEMENT: updated versions: gcc-arm to 10-2020-q4, renode to 1.11.0 and cmake to 3.18.3
Signed-off-by: John Grey <greyjohn734@gmail.com>
> Dockerfile: fixed wget broken dependencies and updated versions

- Dockerfile
This commit adds the `g++-multilib` package to the docker image, which will fix build errors for some 32-bit platforms if we use this docker image to build test cases on 64-bit machines.
Fixes: https://github.com/zephyrproject-rtos/docker-image/issues/48
Signed-off-by: Henry Wang <<Henry.Wang@arm.com>>
> Dockerfile: Add g++-multilib to docker image

- Dockerfile
Added xterm among installation packages in the Dockerfile so you can run the native posix code while monitoring the UART output. Run the docker container with the relevant DISPLAY environment variable and X11 enabled on the host.
> Added xterm among installation packages

- Dockerfile
With these extra packages SDK-ng's Crosstool-NG could be flawlessly built, otherwise fails on configuration step.
> Fixes for Zephyr's SDK-ng's Crosstool-NG

- Dockerfile
doxygen is being removed when clang-10 is uninstalled, do not autoremove
packages to avoid unwanted side effects.
> do not autoremove packages

- Dockerfile
we need a test to verify UEFI bootable method in CI, so I added a test https://github.com/zephyrproject-rtos/zephyr/pull/37287 to verify it on qemu_x86_64 platform, but for this test, it needs external environment uefi-run and ovmf, so I added them into CI docker image.
Signed-off-by: Chen Peng1 <peng1.chen@intel.com>
> image: add uefi-run and ovmf

- Dockerfile
change the installation directory of uefi-run to
/usr/bin, then cmake can find it from system
default path directly.
fix: https://github.com/zephyrproject-rtos/zephyr/issues/37746
Signed-off-by: Chen Peng1 <peng1.chen@intel.com>
> ci: image: update uefi-run installation path

- Dockerfile
Otherwise:
```bash
$ ./go.sh tools
...
########################################################################
Building Zephyr host tools...
########################################################################
MACHINE=qemux86
ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
chrpath cpio diffstat
Error(s) encountered during bitbake.
```
> Satisfy requirements for "tools" building

- Dockerfile
Even though the SDK is installed as 'user', the CMake package folder
(/home/user/.cmake) is owned by root due to 'sudo'. Set ownership
explicitely to fix it.
Without the fix, the SDK is not found by west leading to the following error
message:
CMake Error at /home/user/zephyrproject/zephyr/cmake/verify-toolchain.cmake:75 (find_package):
Could not find a package configuration file provided by "Zephyr-sdk"
(requested version 0.13.1) with any of the following names:
Zephyr-sdkConfig.cmake
zephyr-sdk-config.cmake
Add the installation prefix of "Zephyr-sdk" to CMAKE_PREFIX_PATH or set
"Zephyr-sdk_DIR" to a directory containing one of the above files.  If
"Zephyr-sdk" provides a separate development package or SDK, be sure it has
been installed.
Call Stack (most recent call first): …
> Fix permissions of CMake package path

- Dockerfile
Install the Zephyr SDK 0.14.0 release.
Note that the Zephyr SDK 0.14.0 is no longer distributed in the self-
extracting archive (SFX) format and is now available as a tarball with
a setup script inside.
> Update to Zephyr SDK 0.14.0

- .github/workflows/ci.yml
This commit updates the CI workflow to handle multiple tags when
pushing to the container registry (e.g. `latest` and `vX.Y` tags may
be specified for the CI run on a tag).
> ci: Handle multiple tags for push

- .github/workflows/ci.yml
- Dockerfile
This commit updates the CI workflow to build the CI and Developer
docker images for the `linux/arm64` host.
Closes #90
> ci: Build for linux/arm64 host

- Dockerfile
This commit fixes incorrect ENV command usages in the Dockerfile.
> Dockerfile: Fix incorrect ENV usage

- Dockerfile
This commit adds a step that installs a specific version of Doxygen
binaries because the distro-provided Doxygen package may be outdated
and not the version required for building Zephyr documentation.
Note that the custom Doxygen binaries are only installed for the x86-64
build of the Docker image because the official Doxygen website only
provides the x86-64 binaries.
For this reason, the distro-provided Doxygen package, which is
available for multiple architectures, is still installed so that
Doxygen is available for non-x86 images -- in case of the x86-64 image,
which contains both the distro Doxygen package and the custom Doxygen
installation, the latter takes precedence because it is sym-linked in
`/usr/local/bin`, which takes precedence over `/usr/bin` in PATH.
Signed-off-by: …
> Dockerfile: Add Doxygen installation step

- Dockerfile
Remove the Doxygen binary tarball in the final image since it is not
used after image build.
This commit also fixes hard-coded version numbers in the Doxygen
installation step.
> Dockerfile: Clean up Doxygen tarball after extracting

- .github/workflows/ci.yml
This commit updates the CI workflow to run on the release branches
(v*-branch).
> ci: Run workflow on release branches

- .github/workflows/ci.yml
This commit updates the CI workflow to use a larger 4-core runner.
> ci: Use larger runner

- Dockerfile
This commit reworks the protobuf-compiler (protoc) installation step to use the precompiled binaries instead of the distro package and updates its version to 21.7 because the latest Python protobuf package requires a more up-to-date version than what is provided by the distro.
> Dockerfile: Update protobuf-compiler to 21.7

- .github/workflows/stale-workflow-queue-cleanup.yml
This commit adds a workflow to periodically clean-up the stale workflow runs that are stuck in 'queued' state.
These stale workflow runs can result from occasional GitHub webhook delivery mishaps and may affect the CI autoscaler decision making process.
> ci: Add workflow for cleaning up stale queued workflow runs

- .github/workflows/ci.yml
This commit splits the current "build" job that builds both amd64 and
arm64 images into individual jobs running on the corresponding the host
architecture building each image.
Splitting the image build jobs and building the images on the native
host without using QEMU reduces the build time significantly.
As part of splitting the build jobs, a new "merge" job was introduced
to create single Docker tag containing the manifests for both amd64 and
arm64 images.
> ci: Split multi-arch image builds into individual jobs

- Dockerfile.base
This packages is lagging behind and causing various conflicts. It is
needed for CI in some workflows but not a direct dependency in zephyr.
Signed-off-by: Anas Nashif <anas.nashif@intel.com>
> base: remove awscli to allow pyocd to work

- Dockerfile.base
Add the thrift compiler (code generator).
> base: add thrift dependencies

- Dockerfile.base
We are using for the BT workflow, but it is usefull for developers too.
We can save 10 seconds of CI time per run by not installing it each time.
> Install parallel

- Dockerfile.ci
This commit updates the Zephyr SDK version to 0.16.0-rc1.
Note that the distribution archive format was changed from tar.gz to tar.xz in the SDK 0.16.0 release.
> Dockerfile: Update to Zephyr SDK 0.16.0-rc1

- Dockerfile.base
- Dockerfile.ci
- Dockerfile.devel
Notable dependency changes:
* Use cargo and CMake provided by official Ubuntu repos
Ubuntu 22.04 comes with CMake 3.22 which satisfies Zephyr's requirement of CMake>3.20
* Use `--no-cache-dir` flag for pip install operations
Not caching the installation and source files reduces the image's size without any negative side-effects 
* Remove insecure `--no-check-certificate` wget flag
All wget operations succeed on Ubuntu 22.04 without this flag, and leaving it is asking for supply-chain attacks
* Install renode python requirements
This follows the official `antmicro/renode` [Dockerfile](https://github.com/RenodeBot/renode-docker/blob/master/Dockerfile) steps
* Install llvm/clang manually
The `llvm.sh` autoinstaller fails on Ubuntu 22.04 with some cryptic internal package conflicts.
Running …
> Dockerfile: Upgrade images & deps for Ubuntu 22.04

- Dockerfile.base
This commit removes the `awscli` Python package from the base CI image because it is not currently not used by any Zephyr CI workflows and has `PyYAML` dependency conflict with the Renode (see the GH issue #145).
If the AWS command line tool is necessary in the future, look into either migrating to the `awscliv2` or installing the `awscli` package in a virtual environment.
---
Fixes #145
> Dockerfile: Remove awscli Python package

- Dockerfile.ci
To enable the bsim workflow in the main repository to updates to the manifest version on its own. (eventually)
> bsim: Fetch with west instead of repo (and update from v2.0.1 to v2.1)

- Dockerfile.base
This series upates the base image Dockerfile to source the Python package requirements from the `main` branch instead of the `master` branch of the relevant repositories.
> base: Use main branch to source Python requirements

- Dockerfile.ci
This reverts commit 9c8b9da126ab606eb5217501ea39f4758f9ddca5 because the broken AArch64 packages in the LLVM APT repository have been fixed.
> Revert "ci: Disable LLVM 16 installation for AArch64 image"

- Dockerfile.base
Native boards currently cannot be debugged with `west debug` in the docker images. This PR add GDB to enable debugging for said boards.
> base: Add GDB

- Dockerfile.base
So we can build the native host FUSE access to flash
> Base: Install also libfuse-dev:i386 on x86-64

- Dockerfile.base
After a discussion in Discord
(https://discord.com/channels/720317445772017664/1196766845332619305/1196766847962464276) we concluded that there is no easy way of adding vendor-specific Python packages that are required to be executed during the build but should not be present in the standard requirements-*.txt files since they are specific to a single vendor.
For now solve the issue by including the package by name in the Docker file, to have the package available for the PR that introduced the first IC that requires this package, the nRF54H20 (https://github.com/zephyrproject-rtos/zephyr/pull/68043).
> base: Add nrf-regtool to the list of Python packages installed

- Dockerfile.ci
This commit adds the Kitware ninja v1.11.1 to the CI Docker image.
The Kitware fork of ninja is required to enable the "jobserver" feature, which is currently not available in the upstream ninja codebase.
The ninja jobserver client feature is used by the Zephyr CI workflow in conjunction with the twister-side jobserver to globally limit the number of parallel compilations, which is necessary to keep the runner RAM usage under control.
Note that Kitware ninja is currently only included in the x86-64 image because pre-compiled AArch64 binary is not available -- for AArch64, the distro-provided vanilla ninja will be used.
> ci: Add Kitware ninja v1.11.1

- Dockerfile.ci
This commit adds the ccache v4.9.1, the latest version at the moment, to the CI Docker image because the distro ccache package is relatively outdated and does not support newer features used by the zephyr-runner v2 (mainly, redis remote storage backend).
Note that the upstream ccache project does not distribute pre-compiled AArch64 binary -- for AArch64, the distro-provided ccache package will be used.
> ci: Add ccache 4.9.1

- Dockerfile.base
This commit updates the base image Dockerfile to include nrf-regtool version 5.1.0 or above.
> base: Require nrf-regtool version 5.1.0 or above

- .github/workflows/ci.yml
This commit updates the CI workflow to use the new zephyr-runner v2.
As part of this, it also reworks the workflow to use Buildah and Podman, which is daemon-less and does not require root privileges, to build Docker images because the new runners have more strict security requirements and run workflow pods in unprivileged mode, which effectively makes it impossible to run Docker daemon inside a runner.
> .github: workflows: Use zephyr-runner v2

- Dockerfile.base
The new version is required for the introduction of nrfs, see here: https://github.com/zephyrproject-rtos/zephyr/pull/70245
> base: Bump the nrf-regtool version to 5.2.0

- Dockerfile.base
The new version is required for the introduction of nRF MCAN: https://github.com/zephyrproject-rtos/zephyr/pull/73386
> base: Bump the nrf-regtool version to 5.3.0

- .github/workflows/ci.yml
This commit updates the CI workflow to explicitly configure the Podman container storage to be inside the runner work volume (`__w`), which is guaranteed to have at least 100GB available.
The default container storage path is `/var/lib/containers/storage`, which resides in the Docker storage volume that has no free space guarantees.
> ci: Place container storage inside work volume

- .github/workflows/ci.yml
This commit adds the `--pull-never` flag to the derivative image builds
in order to ensure that the locally built base image is used instead of
a remote pulled one.
Without this flag, buildah may pull the remote tag even if a local copy
with the same tag name exists.
> .github: workflows: Ensure that local base images are used

- Dockerfile.base
We are using junit2html in the CI jobs.
Let's install it in the image to save a bit of time.
> base: Add junit2html

- Dockerfile.ci
Invoke `rust target add ...` for each of the targets supported by Zephyr.  There is a bit of a catch-22 here.  We should be getting this list from the build, but the change that adds Rust support can't merge until Rust support has been tested.
Once the first PR is merged, and the zephyr/lib/rust/targets.txt file exists, the hardcoded list here can be replaced by a loop that adds each of these targest.
All of the targets adds about 300Mb to the image, as these targets only include a fairly minimal 'core' and 'alloc' library.
> ci: Add rust target support

- Dockerfile.base
In tests, users may see a segfault in CI which they may not be able to reproduce locally (due to having a different OS).
A user may try to get more info in CI by running that test with valgrind. But for valgrind to run with 32bit targets we need libc6-dbg:i386 installed.
So let's install it by default so it is ready for users.
> base: Install libc6-dbg:i386

- Dockerfile.base
New fields for configuring the tracing subsystem were added here: https://github.com/zephyrproject-rtos/zephyr/pull/78831 nrf-regtool 6.0.0 supports those latest changes.
> base: Bump nrf-regtool to 6.0.0

- README.md
This commit adds notes about retrieving the correct version of Docker
image for the Zephyr 3.7 LTS.
> README: Add notes about Zephyr 3.7 LTS

- Dockerfile.base
Require nrf-regtool 6.x because 7.x seems to be incompatible with the current Zephyr codebase.
> base: Require nrf-regtool~=6.0.0

- Dockerfile.base
Require nrf-regtool >=5.3.0 and <6.0.0 in order to ensure compatibility with the Zephyr LTS3 codebase.
> [v0.26-branch] base: Require nrf-regtool~=5.3.0

- Dockerfile.base
This is required for additional upcoming features.
> base: Bump nrf-regtool version to 7.0.0

- Dockerfile.ci
This change updates the URL to fetch FPS from as well as installing FVPs for Corstone 315 and 320.
Finally, it now does so for both x86_64 and aarch64 platforms.
> ci: update FVPs’s versions, add Corstone 315 and 320 & enable aarch64 FVPs

- Dockerfile.ci
By default, rustup installs the "latest" stable version of the rust toolchain.  Instead, fix this to a specific version.  This serves two purposes:
- It becomes possible to map a docker image version to a specific version of the rust toolchain that it contains.
- It makes upgrades explicit, especially when features of a specific version are needed.
This sets the version to the current stable version: 1.86.
> Specificy explict rust version

- Dockerfile.base
- Dockerfile.ci
Make sure grpcio-tools is installed to have protoc compiler in python.
> base: Install grpcio-tools

- Dockerfile.base
- Dockerfile.ci
- Dockerfile.devel
- README.md
Adding a USERNAME build argument so that the ssh-agents will work (they require the username inside the container to be the same as the user name that is running the ssh-agent.  This is an optional argument so if they don't use it, it defaults to `user` as before.
I ran into a problem with getting the entrypoint.sh path to work with the ${USERNAME} variable so I just punted and put the entrypoint.sh in the `/user` directory.  If anyone knows how to get it to work, please speak up :)
> Add USERNAME build argument

- .github/workflows/ci.yml
The Hetzner Ubuntu mirror is only available within the Hetzner network and thereby Hetzner-hosted runners.
This commit updates the CI workflow to specify the Hetzner Ubuntu mirror only if the scheduled runners are hosted by Hetzner.
> .github: workflows: Use Hetzner Ubuntu mirror on Hetzner runners only

- Dockerfile.ci
Matches official install recommendations and also fixes apt-key issues.
Fixes #239 and #242
> Use dotnet instead of mono and use renode portable

- .github/workflows/ci.yml
Do not cancel the rest of the jobs when one of the jobs in the matrix fails.
> .github: workflows: Do not fail fast

- Dockerfile.base
One of the i386 packages installed in the base Docker image depends on `python3-minimal` and APT tries to nuke the previously installed `python3` and all its friends, including `software-properties-common`, during the i386 package installation.
Marking `python3` and `python3-apt` as held seems to make APT not want to do that, and keeps `python3` and its friends in place without any hacks.
This should, hopefully, be the ultimate fix for all the i386 package dependency issues we have come across in the past.
> base: Fix i386 APT package dependency hell

- Dockerfile.devel
This commit removes the hard-coded `ZEPHYR_BASE` environment variable from the Developer image to allow more flexibility for the user Zephyr tree layout.
With this change, it is now up to the user to provide the adequate environment configuration (e.g. setting `ZEPHYR_BASE` environment variable, or providing west configuration file with Zephyr base path) for Zephyr source root discovery.
---
Closes https://github.com/zephyrproject-rtos/docker-image/issues/162
> devel: Remove hard-coded ZEPHYR_BASE environment variable

- Dockerfile.base
The LLVM APT repository does not provide i386 packages and this leads to package version conflicts when an i386 package pulls the `libllvm` package as a dependency (refer to the issue #269 for more details).
Since Ubuntu 24.04 provides the LLVM/Clang 20 packages, use those to avoid package version conflicts.
---
Fixes https://github.com/zephyrproject-rtos/docker-image/issues/269
> base: Switch to distro-provided LLVM/Clang packages

- Dockerfile.base
```
fuse v3 has been out there for a few years,
and many other components have been progressively switching to it, 
while some distros have been taking an active effort to ensure they do
not use the old fuse(2) anymore and intend to deprecate it in favor of
fuse3 and remove it.
The native_sim fuse driver now can use fuse3 also, so let's install libfuse3-dev
in our docker image to do a calm and progressive transition to it.
i.e.:
1. Zephyr supports fuse3, but defaults to using v2 so we are compatible with the old image
2. The docker image starts including v3
3. Zephyr defaults to use v3
4. The docker image does not need to have v2 anymore so we remove it
1. is done
2. we'd want to do as soon as possible to enable other steps and forwards compatibility of the image
4. could then be done at …
```
> base: Add libfuse3

- Dockerfile.base
We forgot it in 585e01d038c58926ae55a574a4b7ec8389cd7e9f and that includes the libraries needed for building w sanitizers, fuzzer, etc.
> base: Also install libclang-rt-*-dev
